In [7]:
import pandas as pd

df = pd.read_csv("highest_grossing_films.csv")

df.head()

   Rank Peak                     Title   Worldwide gross  Year
0     1    1                    Avatar    $2,923,710,708  2009
1     2    1         Avengers: Endgame    $2,797,501,328  2019
2     3    3  Avatar: The Way of Water    $2,334,484,620  2022
3     4    1                   Titanic   T$2,257,906,828  1997
4     5    5                  Ne Zha 2  NZ$2,215,690,000  2025

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rank             50 non-null     int64
 1   Peak             50 non-null     object
 2   Title            50 non-null     object
 3   Worldwide gross  50 non-null     object
 4   Year             50 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

In [9]:
df.describe(include="all")

            Rank Peak   Title Worldwide gross         Year
count   50.00000   50      50              50    50.000000
unique       NaN   25      50              50          NaN
top          NaN    3  Avatar  $2,923,710,708          NaN
freq         NaN    6       1               1          NaN
mean    25.50000  NaN     NaN             NaN  2016.200000
std     14.57738  NaN     NaN             NaN     6.204015
min      1.00000  NaN     NaN             NaN  1997.000000
25%     13.25000  NaN     NaN             NaN  2013.000000
50%     25.50000  NaN     NaN             NaN  2017.500000
75%     37.75000  NaN     NaN             NaN  2019.000000
max     50.00000  NaN     NaN             NaN  2025.000000

In [10]:
df.shape

(50, 5)

In [11]:
df.isnull().sum()

Rank               0
Peak               0
Title              0
Worldwide gross    0
Year               0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Year"].value_counts().sort_index()

Year
1997    1
1999    1
2003    1
2006    1
2009    1
2010    1
2011    3
2012    3
2013    2
2014    1
2015    5
2016    2
2017    3
2018    5
2019    9
2021    1
2022    2
2023    2
2024    3
2025    3
Name: count, dtype: int64

In [16]:
df["Worldwide gross"] = (
    df["Worldwide gross"]
    .astype(str)
    .str.replace(r"[^\d]", "", regex=True)
)

df["Worldwide gross"] = pd.to_numeric(df["Worldwide gross"])

In [17]:
df["Worldwide gross"].describe()

count    5.000000e+01
mean     3.039353e+09
std      1.129389e+10
min      1.045714e+09
25%      1.112394e+09
50%      1.320508e+09
75%      1.622411e+09
max      8.123876e+10
Name: Worldwide gross, dtype: float64

In [18]:
df[["Title", "Worldwide gross"]].head(10)

                          Title  Worldwide gross
0                        Avatar       2923710708
1             Avengers: Endgame       2797501328
2      Avatar: The Way of Water       2334484620
3                       Titanic       2257906828
4                      Ne Zha 2       2215690000
5  Star Wars: The Force Awakens       2068223624
6        Avengers: Infinity War       2048359754
7       Spider-Man: No Way Home       1922598800
8                  Zootopia 2 †       1866647950
9                  Inside Out 2       1698863816